info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:25:43.821Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:25:43.855Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:25)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T02:32:38.635Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:47:59.570Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:47:59.598Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: undefined, UserID: undefined }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T02:48:08.225Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:48:42.397Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:48:42.425Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:50:44.301Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:50:44.321Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: undefined, UserID: undefined }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T02:50:52.726Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:54:44.875Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:54:44.948Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:56:51.092Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:56:51.119Z"}
error: 
    status - 500 
    message - ReferenceError: _UserId is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:40:17)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T02:57:01.967Z"}
error: 
    status - 500 
    message - ReferenceError: _UserId is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:40:17)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T02:57:33.638Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:58:09.729Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:58:09.768Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:43:12)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T02:58:14.482Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T02:59:12.056Z"}
info: Connected to the database. {"timestamp":"2022-07-01T02:59:12.078Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:43:12)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T02:59:18.465Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T03:00:26.057Z"}
info: Connected to the database. {"timestamp":"2022-07-01T03:00:26.091Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T03:05:33.357Z"}
info: Connected to the database. {"timestamp":"2022-07-01T03:05:33.392Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T05:21:55.600Z"}
info: Connected to the database. {"timestamp":"2022-07-01T05:21:55.820Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T05:23:18.552Z"}
info: Connected to the database. {"timestamp":"2022-07-01T05:23:18.582Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T05:23:46.545Z"}
info: Connected to the database. {"timestamp":"2022-07-01T05:23:46.569Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndDelete (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:2834:19)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:56:29)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:55:23)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:90:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/userNotes/62be642e0589740f0cfe05b6/isDelete 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-07-01T05:24:44.713Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T05:25:23.923Z"}
info: Connected to the database. {"timestamp":"2022-07-01T05:25:23.949Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:58:13)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:55:23)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:90:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62be642e0589740f0cfe05b6/isDelete 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-07-01T05:25:27.671Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T05:28:08.577Z"}
info: Connected to the database. {"timestamp":"2022-07-01T05:28:08.615Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T05:28:22.131Z"}
info: Connected to the database. {"timestamp":"2022-07-01T05:28:22.157Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:58:13)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:55:23)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:90:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62be642e0589740f0cfe05b6/isDelete 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-07-01T05:28:32.074Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-01T05:29:11.728Z"}
info: Connected to the database. {"timestamp":"2022-07-01T05:29:11.758Z"}
